package gcp

// topPerms is the first chunk of permissions tested via testIamPermissions.
var topPerms = []string{
	"iam.serviceAccounts.list",
	"iam.serviceAccounts.get",
	"iam.serviceAccounts.getAccessToken",
	"iam.serviceAccounts.signBlob",
	"iam.serviceAccounts.signJwt",
	"iam.serviceAccounts.setIamPolicy",
	"iam.serviceAccounts.getIamPolicy",
	"iam.serviceAccounts.actAs",
	"iam.serviceAccounts.implicitDelegation",
	"iam.serviceAccounts.create",
	"iam.serviceAccounts.delete",
	"iam.serviceAccounts.update",
	"iam.serviceAccountKeys.list",
	"iam.serviceAccountKeys.get",
	"iam.serviceAccountKeys.create",
	"iam.serviceAccountKeys.delete",
	"resourcemanager.projects.get",
	"resourcemanager.projects.list",
	"resourcemanager.projects.getIamPolicy",
	"resourcemanager.projects.setIamPolicy",
	"resourcemanager.projects.testIamPermissions",
	"resourcemanager.organizations.get",
	"resourcemanager.organizations.getIamPolicy",
	"resourcemanager.folders.list",
	"resourcemanager.folders.getIamPolicy",
	"storage.buckets.list",
	"storage.buckets.get",
	"storage.buckets.getIamPolicy",
	"storage.objects.list",
	"storage.objects.get",
	"storage.objects.create",
	"container.clusters.list",
	"container.clusters.get",
	"container.clusters.getCredentials",
	"container.clusters.create",
	"container.clusters.update",
	"compute.instances.list",
	"compute.instances.get",
	"compute.instances.setMetadata",
	"compute.instances.setIamPolicy",
	"compute.instances.getIamPolicy",
	"compute.instances.use",
	"compute.zones.list",
	"compute.networks.list",
	"compute.subnetworks.list",
	"compute.firewalls.list",
	"compute.projects.setCommonInstanceMetadata",
	"compute.osLogin.get*",
	"secretmanager.secrets.list",
	"secretmanager.secrets.get",
	"secretmanager.versions.access",
	"secretmanager.locations.list",
	"cloudkms.keyRings.list",
	"cloudkms.cryptoKeys.list",
	"cloudkms.cryptoKeyVersions.list",
	"cloudkms.cryptoKeys.getIamPolicy",
	"cloudkms.cryptoKeys.setIamPolicy",
	"cloudkms.cryptoKeyVersions.useToDecrypt",
	"cloudfunctions.functions.list",
	"cloudfunctions.functions.get",
	"cloudfunctions.functions.call",
	"cloudfunctions.functions.sourceCodeGet",
	"pubsub.topics.list",
	"pubsub.subscriptions.list",
	"pubsub.snapshots.list",
	"bigquery.datasets.list",
	"bigquery.tables.list",
	"sql.instances.list",
	"sql.instances.get",
	"sql.users.list",
	"artifactregistry.repositories.list",
	"artifactregistry.packages.list",
	"dns.managedZones.list",
	"logging.logEntries.list",
	"logging.sinks.get",
	"serviceruntime.services.list",
	"serviceruntime.quotas.get",
	"serviceusage.services.list",
	"serviceusage.services.get",
	"dataproc.clusters.list",
	"cloudbuild.builds.list",
	"cloudbuild.builds.get",
	"run.services.list",
	"run.jobs.list",
	"remotebuildexecution.blobs.get",
	"orgpolicy.policy.get",
	"securitycenter.findings.list",
	"recommender.roleinsights.list",
}

var permHints = map[string]string{
	"iam.serviceAccounts.getAccessToken":         "impersonate any SA in the project: generate access token, tokenSource default SA",
	"iam.serviceAccountKeys.create":              "create a static key for any SA: full identity theft, no scope limits",
	"iam.serviceAccountKeys.list":                "find existing static keys; export them to bypass metadata scopes",
	"iam.serviceAccounts.actAs":                  "actAs any SA you can build a resource with",
	"iam.serviceAccounts.setIamPolicy":           "grant yourself actAs/getAccessToken over target SAs",
	"resourcemanager.projects.setIamPolicy":      "grant yourself any project role, including owner",
	"resourcemanager.folders.getIamPolicy":       "read org-wide IAM to map escalation paths",
	"container.clusters.getCredentials":          "pull kubeconfig for any GKE cluster in the project",
	"container.clusters.create":                  "create a GKE cluster and be its admin",
	"storage.buckets.get":                        "read bucket contents without list — brute names from naming patterns",
	"storage.objects.get":                        "download bucket objects — check for terraform state, backups, creds",
	"compute.instances.setMetadata":              "append attacker SSH key to project metadata, then SSH to VMs",
	"compute.projects.setCommonInstanceMetadata": "project-wide SSH key injection = full VM takeover",
	"secretmanager.versions.access":              "read every Secret Manager secret version",
	"cloudkms.cryptoKeyVersions.useToDecrypt":    "decrypt data protected by the project KMS",
	"cloudfunctions.functions.sourceCodeGet":     "download function source — hunt embedded secrets",
	"cloudfunctions.functions.setIamPolicy":      "grant yourself invoker then weaponize the function",
	"sql.instances.get":                          "cloud SQL may hold business data; look for sql.users.list too",
	"serviceusage.services.enable":               "enable APIs the project has turned off",
	"dns.managedZones.list":                      "map internal DNS zones for service discovery",
	"resourcemanager.organizations.getIamPolicy": "check org-level grants — a compromise here covers all projects",
}
